### PR TITLE
Add contract profiling instrumentation.

### PR DESCRIPTION
**Pull request by stamourv**

### CODE REVIEW

**Comment by AlexKnauth** [comment]
Can this be made to work with the earlier versions of racket?

**Comment by stamourv** [comment]
I think so.
If you replace `with-contract-continuation-mark` with `with-continuation-mark contract-continuation-mark-key`, that should be equivalent, and should only rely on things that have been exported for a while.

**Comment by AlexKnauth** [comment]
So could you do that?

**Comment by stamourv** [comment]
Done.

**Comment by AlexKnauth** [comment]
Thanks!

**Pull request merged**
